# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about'}
- {name: 'Teaching', path: 'menu', url: 'teaching'}
- {name: 'Projects', path: 'menu', url: 'projects'}
- {name: 'Papers', path: 'menu', url: 'papers'}
- {name: 'Ln', path: 'menu', url: 'ln'}
- {name: 'Contact', path: 'menu', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/davidnkraemer'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/davidnkraemer'}
- {icon: 'envelope', link: 'mailto:david.kraemer@stonybrook.edu'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'If you liked this post, feel free to share it:'

related_posts: 'Related Lns:'

post_date_prefix: 'Published on'
